// Static blog content — no CMS/DB, matches the pattern used by FAQ.jsx and
// Roadmap.jsx (hardcoded content array, edited directly in code). Add new
// posts by appending an entry here; Blog.jsx and BlogPost.jsx pick them up
// automatically.
//
// content blocks: { type: 'p', text } | { type: 'h2', text } | { type: 'ul', items: string[] }

export const BLOG_POSTS = [
  {
    slug: 'how-to-run-a-fair-skins-game',
    title: 'How to Run a Fair Skins Game',
    excerpt: 'Skins games are one of the easiest ways to add stakes to a casual round — but only if the rules are set before the first tee shot. Here\'s how to avoid the most common disputes.',
    date: '2026-08-11',
    category: 'Side Games',
    content: [
      { type: 'p', text: 'A skins game is simple in theory: whoever has the lowest score on a hole wins that hole\'s "skin." If two or more players tie for low score, the skin carries over to the next hole, growing the pot. In practice, most disputes come from ambiguity that was never resolved before the round started — not from the format itself.' },
      { type: 'h2', text: 'Decide gross or net before you tee off' },
      { type: 'p', text: 'Playing skins on gross score rewards your lowest-handicap players and can shut out higher handicappers from ever winning a hole. Playing net (applying handicap strokes on a hole-by-hole basis) levels the field, but requires everyone to know their course handicap and stroke allocation ahead of time. Most weekly leagues use net skins for exactly this reason — it keeps the game competitive for the whole field, not just the scratch players.' },
      { type: 'h2', text: 'Decide how ties and carryovers work' },
      { type: 'p', text: 'The most common format is "ties carry" — if two players tie for low score on a hole, no one wins it, and the value rolls into the next hole. Some groups instead split the skin between tied players rather than carrying it. Either is fine, but pick one before the round; switching mid-round after a controversial tie is where most arguments start.' },
      { type: 'h2', text: 'Set the buy-in and payout structure in advance' },
      { type: 'p', text: 'Common structures: a flat per-player buy-in with the full pot split among skin winners, or a fixed dollar value per skin with any leftover carryover skins paid out at the 18th hole. If you\'re running a larger group split into flights, decide whether skins are computed within each flight separately or across the full field — this changes the competitive dynamic significantly.' },
      { type: 'h2', text: 'Track it digitally to kill disputes before they start' },
      { type: 'p', text: 'The single biggest source of skins-game disputes is a handwritten scorecard with an ambiguous number, discovered after everyone has already left the course. Digital, hole-by-hole scoring — where every player\'s score is entered and visible in real time — removes the ambiguity entirely and settles the skins table automatically the moment the last group finishes.' },
    ],
  },
  {
    slug: 'flights-vs-full-field',
    title: 'Flights vs. Full Field: Choosing the Right Format for Your League',
    excerpt: 'Splitting your league into flights can make competition fairer — or it can just add complexity for no benefit. Here\'s how to know which format actually fits your group.',
    date: '2026-08-28',
    category: 'League Setup',
    content: [
      { type: 'p', text: 'One of the first decisions a new league admin faces is whether to run the whole field as one competition or split players into flights by handicap. Both are valid — the right choice depends on the size and skill spread of your group.' },
      { type: 'h2', text: 'When a full field makes sense' },
      { type: 'p', text: 'If your league is small (under roughly 16-20 players) or has a fairly tight handicap spread, a single full-field leaderboard is usually simpler and more fun — everyone is chasing the same standings, and net scoring already handles most of the fairness concerns. Extra flights on a small group can leave you with a "flight" of two or three players, which feels more like an arbitrary label than real competition.' },
      { type: 'h2', text: 'When flights make sense' },
      { type: 'p', text: 'Once your league grows past that range, or if you have a wide handicap spread (say, players ranging from scratch to 30+), flights keep the competition meaningful. A typical setup is two or three flights (A/B/C) based on handicap index, each with its own leaderboard, payouts, and season standings. This way a higher-handicap player is competing against others at a similar skill level rather than chasing scores they realistically can\'t catch.' },
      { type: 'h2', text: 'Re-evaluate flight cutoffs each season' },
      { type: 'p', text: 'Handicaps move. A player who started the season in Flight B might legitimately belong in Flight A by mid-season. Most leagues set flight cutoffs once per season (at signup) rather than recalculating mid-season, which keeps standings stable — but it\'s worth revisiting the cutoff handicaps each new season rather than reusing last year\'s numbers by default.' },
      { type: 'h2', text: 'Don\'t forget side games when you flight the field' },
      { type: 'p', text: 'If you\'re running flights, decide whether side games — skins, closest-to-the-pin, long drive — are scored within each flight or across the whole field. Flighted skins games in particular tend to feel fairer to higher-handicap players, since they\'re not just feeding skins to the lowest-handicap flight every week.' },
    ],
  },
  {
    slug: 'golf-handicaps-for-league-play',
    title: "A Beginner's Guide to Golf Handicaps for League Play",
    excerpt: 'If you\'re setting up a league and handicaps feel confusing, you\'re not alone. Here\'s a plain-English breakdown of what actually matters for weekly league play.',
    date: '2026-09-15',
    category: 'Scoring & Handicaps',
    content: [
      { type: 'p', text: 'Handicaps exist to let players of different skill levels compete fairly against each other. For casual league play, you don\'t need to understand every detail of the USGA/WHS calculation — you just need to know a few practical things.' },
      { type: 'h2', text: 'Handicap Index vs. Course Handicap' },
      { type: 'p', text: 'A player\'s Handicap Index is a portable number that follows them between courses — it reflects their general skill level. Their Course Handicap is that index converted for the specific course and tees being played that day, based on the course\'s slope and rating. In league play, what actually determines strokes given on the scorecard is the Course Handicap, not the raw Handicap Index — so the same player will have a different Course Handicap at a harder course than an easier one.' },
      { type: 'h2', text: 'Where the strokes actually go' },
      { type: 'p', text: 'Course Handicap strokes are distributed across holes according to that course\'s stroke index (sometimes called the handicap rating) for each hole — printed on the scorecard, typically 1 through 18 in order of difficulty. A player with a Course Handicap of 9 gets one extra stroke on the nine hardest-rated holes. This is what makes net scoring possible on a hole-by-hole basis, which matters for side games like net skins.' },
      { type: 'h2', text: 'GHIN numbers and posting scores' },
      { type: 'p', text: 'Players who maintain an official Handicap Index typically do so through their state or regional golf association using a GHIN number, and are expected to post eligible scores after each round so their index stays current. Casual leagues that don\'t require an official GHIN can still run a simplified in-house handicap — usually an average of recent net-of-par scores — which is easier to manage but won\'t be portable outside the league.' },
      { type: 'h2', text: 'Keep it current, not perfect' },
      { type: 'p', text: 'The most common mistake in league play isn\'t using the wrong handicap formula — it\'s letting handicaps go stale for an entire season. A player who improves significantly over a summer but keeps their early-season handicap will have an unfair edge in net competitions. Whatever system you use, revisit and update handicaps periodically rather than setting them once and forgetting them.' },
    ],
  },
  {
    slug: 'scorify-vs-golf-league-tracker',
    title: 'Scorify Golf vs. Golf League Tracker: Which One Fits Your League?',
    excerpt: 'Both platforms handle handicaps, live scoring, and standings for independent leagues. Here\'s how they actually differ, and which type of league director each one is built for.',
    date: '2026-09-22',
    category: 'Comparisons',
    content: [
      { type: 'p', text: 'If you\'re running an independent golf league and have outgrown spreadsheets and group texts, Golf League Tracker and Scorify Golf are two of the platforms you\'ll likely come across. Both automate handicaps, live scoring, and standings. The real difference between them isn\'t features on a checklist — it\'s how much setup and configuration you\'re willing to do before you can run a round.' },
      { type: 'h2', text: 'At a glance' },
      { type: 'table', headers: ['', 'Scorify Golf', 'Golf League Tracker'], rows: [
        { label: 'Starting price', a: 'Free (1 league, up to 16 players)', b: '$119/season per league after a 4-round trial' },
        { label: 'Setup style', a: 'Opinionated defaults, live same day', b: '250+ configuration settings' },
        { label: 'Mobile scoring', a: 'No login, no app download', b: 'Mobile-capable, account-based' },
        { label: 'Side games', a: 'Auto gross & net skins, Closest to the Pin', b: 'Skins contests, sub-request tracking' },
        { label: 'Team season format', a: 'Team Play — points across a full season', b: 'Not a standard offering' },
        { label: 'Best fit', a: 'Weekly / monthly / seasonal leagues', b: 'Simulator & disc golf leagues, complex formats' },
      ] },
      { type: 'p', text: 'Prices and features above reflect each provider\'s public site as of this post\'s publish date and are subject to change — always confirm current details directly with each provider before deciding.' },
      { type: 'h2', text: 'Setup and configuration' },
      { type: 'p', text: 'Golf League Tracker has been around a long time and has grown to support an enormous range of formats — it publishes more than 250 configuration settings, covering everything from simulator leagues to disc golf. That flexibility is real, but it comes with a learning curve: a new admin has to work through a lot of screens before their first event is ready to go. Scorify Golf takes the opposite approach — it\'s opinionated by design, with sensible defaults for the formats a typical weekly or seasonal league actually uses (stroke play, net skins, match play, Team Play), so a league director can build their tee sheet and go live the same day.' },
      { type: 'h2', text: 'Live scoring experience' },
      { type: 'p', text: 'Both platforms support mobile score entry so players aren\'t handing a paper card to one overworked scorer at the end of the round. Scorify is built mobile-first from the ground up — players scan a QR code or follow a link and start entering scores hole-by-hole with no app download and no login required, and the leaderboard updates in real time as groups finish holes. Tap any screen below to see it full-size.' },
      { type: 'liveScoring' },
      { type: 'h2', text: 'Live leaderboard, example' },
      { type: 'p', text: 'Here\'s what a live leaderboard looks like mid-round, using sample data — no real players or scores.' },
      { type: 'leaderboard', title: 'Wednesday Night League — Live Leaderboard (Sample Data)', rows: [
        { rank: 1, name: 'J. Alvarez', thru: 14, score: '-3' },
        { rank: 2, name: 'M. Chen', thru: 15, score: '-2' },
        { rank: 3, name: 'S. Patel', thru: 13, score: '-1' },
        { rank: 4, name: 'D. Nguyen', thru: 16, score: 'E' },
        { rank: 5, name: 'R. Foster', thru: 12, score: '+1' },
      ] },
      { type: 'h2', text: 'Side games and team formats' },
      { type: 'p', text: 'Golf League Tracker covers the standard stroke play, match play, Stableford, and best-ball formats you\'d expect from a mature platform, plus skins contests and sub-request tracking. Scorify adds a few things purpose-built for the "regular weekly group" use case: automatic gross and net skins, printable cart signs and Closest to the Pin signs for round day, and Team Play — a season-long team points format for leagues that split players into teams and track standings across a full season — something that isn\'t a standard part of most league platforms.' },
      { type: 'p', text: 'Round-day print assets are built in and ready before the first tee time — examples below use sample data.' },
      { type: 'printAssets' },
      { type: 'h2', text: 'Pricing and getting started' },
      { type: 'p', text: 'Golf League Tracker\'s free trial covers your first 4 rounds (League Manager) or 10 scores per player (Handicap Manager); after that, League Manager pricing starts at $119 per league for a season (up to 30 rounds), with volume discounts down to $89/league for 10+ leagues, plus optional add-ons like the Image/Document Gallery and Premium E-mail at $20/season each. Scorify Golf\'s Starter plan is free indefinitely for one league up to 16 players — no credit card required — and Pro (unlimited players, up to 2 leagues, flights, skins, Closest to the Pin, and CSV export) runs $29/month or $199/year. Either way, organizers collect player dues through their own Venmo or PayPal link rather than routing payments through the platform, so neither service takes a cut of buy-ins.' },
      { type: 'h2', text: 'Which one should you use?' },
      { type: 'p', text: 'If you\'re running a simulator league, a disc golf league, or a format unusual enough that you need deep configurability and don\'t mind the setup time, Golf League Tracker\'s flexibility and long track record are real advantages. If you\'re an independent director running a standard weekly, monthly, or seasonal golf league — and you\'d rather be playing than configuring settings — Scorify is built specifically for that: fast setup, mobile-first scoring, and season-long Team Play standings without a 200-option config screen standing between you and your first tee time.' },
    ],
  },
  {
    slug: 'running-a-golf-league-commissioners-handbook',
    title: "Running a Golf League: The Commissioner's Handbook",
    excerpt: 'What actually works after a season of running a 40-player monthly league — from booking courses six months out to handling the money, the flights, and the guest policy that caused the one real fight all year.',
    date: '2026-10-02',
    category: 'League Management',
    content: [
      { type: 'p', text: 'Running a golf league is one of the most rewarding things you can do in the game. It is also a lot more work than most people expect when they say yes to being commissioner.' },
      { type: 'p', text: 'I help run a monthly league in San Diego with two other admins. We have 40 players on the roster, a waitlist of people who want in, and 28 to 32 golfers teeing it up each month. We play a consistent format with two flights, track season-long standings, run a team competition, and finish the year with playoffs.' },
      { type: 'p', text: 'This year I took a more active role in running the league, and I used that opportunity to launch Scorify Golf, league management software that organizers anywhere can use. Everything in this handbook comes from what has worked for us, what has not, and what I would tell any new commissioner before their first season.' },

      { type: 'h2', text: "Don't Run Your League Alone" },
      { type: 'p', text: 'The first piece of advice I give anyone starting a league is to build a small team of organizers. Getting a league in order each season, and each month, is a team effort.' },
      { type: 'p', text: 'Our league has three admins. Two of them focus on locking down courses and tee times, and they also plan the handful of special league events we hold throughout the year. Splitting the work this way means no single person carries the whole season.' },
      { type: 'h3', text: 'Use the Skills Your Organizers Already Have' },
      { type: 'p', text: 'One thing we learned quickly is that our day jobs make us better at running the league. Between the three of us, our careers cover planning, organizing, operations, finances, and execution. Those are exactly the skills a league needs.' },
      { type: 'p', text: 'When you recruit co-organizers, think about what each person does well and give them ownership of that piece. A natural planner should own the calendar. Someone comfortable with numbers should own the money. Most importantly, lean on each other. When one admin gets busy at work or misses a month, the league keeps running.' },

      { type: 'h2', text: 'Plan Your Season Further Ahead Than You Think' },
      { type: 'p', text: 'Good courses fill up fast, especially on weekends. We book course reservations and tee times six months or more in advance. That lead time is the only way to guarantee availability for a group of 30.' },
      { type: 'h3', text: 'A Monthly Event Timeline That Works' },
      { type: 'p', text: 'Here is the rhythm we follow for each monthly event:' },
      { type: 'ul', items: [
        'Six or more months out: lock in the course and tee times.',
        'Three to four weeks out: send the official announcement and open registration.',
        'Tournament day: players score on their phones as they play, and the leaderboard updates live.',
        'The next morning: results, standings, and payouts are final.',
      ] },
      { type: 'p', text: 'Three to four weeks of notice gives players enough time to plan around work and family, without the event drifting so far out that people forget to sign up.' },
      { type: 'h3', text: 'Where the Time Used to Go' },
      { type: 'p', text: 'Before we moved to digital scoring, tournament day ended with someone stuck at a table entering scorecards by hand. That took close to 90 minutes, while everyone else was socializing. Final results and payouts then took three to four days to sort out. Today, the same work is finished by the next morning.' },

      { type: 'h2', text: 'Keep the Playing Field Even With Flights and Handicaps' },
      { type: 'p', text: 'An even playing field is one of the reasons people keep coming back. If the same low handicappers win every month, the rest of the league eventually loses interest.' },
      { type: 'h3', text: 'Require an Active Handicap Index' },
      { type: 'p', text: "Handicap monitoring is a must. Every player in our league is required to have an active GHIN handicap index. We build the cost of a GHIN membership into annual dues, unless a player already has one through another club." },
      { type: 'p', text: "This removes the guesswork. Everyone's handicap is official, posted, and updated, so nobody has to take anyone's word for it." },
      { type: 'h3', text: 'Split Flights by Handicap Index Only' },
      { type: 'p', text: 'We split players into Flight A and Flight B based strictly on handicap index. No exceptions and no judgment calls. That keeps the process simple and hard to argue with.' },
      { type: 'p', text: 'We also assign different tees by flight. This creates a detail that surprises some players: once course handicaps are calculated from different tees, the top of Flight B can end up with a lower course handicap than the bottom of Flight A.' },
      { type: 'p', text: 'We have not had real complaints about fairness, and I think that is because we explain this upfront. Flights are split by handicap index first, before course handicaps come into play. When players understand the order of operations, the numbers make sense.' },

      { type: 'h2', text: 'Handle the Money Before Anyone Tees Off' },
      { type: 'p', text: 'Money is where leagues get messy, so we keep it simple: everything is prepaid. Players register online and pay through Venmo before the event. For day-of side competitions, we also accept cash.' },
      { type: 'h3', text: 'The Competitions We Run Every Month' },
      { type: 'p', text: 'Side games are a big part of what makes league day fun. Each month, we pay out on:' },
      { type: 'ul', items: ['Overall Net', 'Front 9 Net', 'Back 9 Net', 'Skins', 'Closest to the Pin', 'Long Drive', 'Fewest Putts'] },
      { type: 'h3', text: 'Payout Math Was the Biggest Headache' },
      { type: 'p', text: 'Our biggest money headache was always calculating payouts. With seven competitions across two flights and 30 players, working out who won what by hand took a long time and left room for mistakes. With Scorify, that calculation is now automatic and easy.' },
      { type: 'p', text: 'If you are starting out, decide your payout structure before the season begins and write it down. Players care much less about the exact split than about knowing it is consistent every month.' },

      { type: 'h2', text: 'Put Your Rules in Writing' },
      { type: 'p', text: 'Every league needs bylaws, and every player should see them before the season starts. We share ours with the full league before each season begins. We have made very few changes since the league started, which tells me that getting them right early pays off for years.' },
      { type: 'h3', text: 'Policies Worth Deciding Upfront' },
      { type: 'p', text: 'These are the policies I recommend every league settle before the first event:' },
      { type: 'ul', items: [
        'Prepaid entry: everyone pays when they register, not on the first tee.',
        'A 24-hour cancellation window: players who cancel at least 24 hours before the event are covered. No-shows and late cancellations forfeit their entry.',
        'Active GHIN required: every player must carry an official handicap index, and we include the cost in annual dues.',
        'A clear guest policy for side games: decide before the season whether guests can enter the pots. We learned this one the hard way, as explained below.',
      ] },
      { type: 'p', text: 'Clear policies protect you as the commissioner. When a tough situation comes up, you can point to the bylaws instead of making a judgment call that feels personal.' },

      { type: 'h2', text: 'Communicate Clearly and Build Community' },
      { type: 'p', text: 'A league is more than a monthly tee time. The leagues that last give players reasons to stay connected between events.' },
      { type: 'h3', text: 'Keep Communication in One Place' },
      { type: 'p', text: 'Email is our primary way of reaching players. Every event announcement points to a single event page where players can see the details, register online, and pay their entry fee. One link replaces the long text threads that used to ask who was in, what time, and which course.' },
      { type: 'p', text: 'We also run an active Instagram page with photos and videos from every event. It keeps members engaged between rounds, and it shows prospective members what they are missing.' },
      { type: 'h3', text: 'Give Players Something to Play For All Year' },
      { type: 'p', text: 'A single round is fun. A season with stakes is what keeps people coming back every month. We layer several competitions on top of each event:' },
      { type: 'ul', items: [
        'Season-long standings that update after every tournament',
        'A team play competition that runs across the full season',
        'Playoffs at the end of the year for the top 8 money winners',
      ] },
      { type: 'h3', text: 'Create Traditions' },
      { type: 'p', text: 'Our biggest event of the year is not a tournament. It is the banquet we hold each January after the first event of the season. It kicks off the year, brings everyone together off the course, and sets the tone for the months ahead.' },
      { type: 'p', text: 'We also give members a gift each year. Recent examples include golf towels, hats, and shoe cases. Small touches like these make the league feel like a club, not just a schedule.' },
      { type: 'h3', text: 'Help Members Get to Know Each Other' },
      { type: 'p', text: 'If I could only give one piece of advice on community, it would be this: get your members acquainted with one another. A larger group helps, but only if people actually connect. Mix up pairings so players meet new people, and use events like the banquet to bring the group together.' },

      { type: 'h2', text: 'Choose Tools That Make the Job Easier' },
      { type: 'p', text: 'For years, our league ran on spreadsheets. They worked, but every task depended on someone entering data by hand, and every manual step was a chance for an error or a delay.' },
      { type: 'h3', text: 'What I Tried Before Building My Own' },
      { type: 'p', text: 'I tried a couple of popular golf scoring apps, but both had serious limitations for how our league runs. The biggest one was that every player had to download an app to score live. In a group of 30 golfers, someone always has trouble with the download, the login, or their phone.' },
      { type: 'p', text: 'A frustrating user experience in one of those apps was the final push. I wanted something simpler for our players and our admins, so I built Scorify Golf.' },
      { type: 'h3', text: 'What to Look for in League Software' },
      { type: 'p', text: 'Whatever tool you choose, here is what I would look for based on running our league:' },
      { type: 'ul', items: [
        "No app download for players. Scoring should work from any phone's web browser.",
        'Online registration with payment links, so entry fees are collected before the round.',
        'Live scoring and leaderboards, so results are ready when the round ends.',
        'Automatic side game and payout calculations.',
        'Flight support and season-long standings.',
        'Handicap tracking built in.',
      ] },
      { type: 'p', text: 'The right tool should give time back to the people running the league. For us, that meant going from 90 minutes at the scoring table and three to four days of follow-up to final results by the next morning.' },

      { type: 'h2', text: 'Lessons Learned the Hard Way' },
      { type: 'h3', text: 'Think Twice Before Letting Guests Into Side Games' },
      { type: 'p', text: 'Our biggest mistake was letting guests participate in the side games and bets. It seemed harmless and welcoming at the time. Then a few guests took home substantial winnings, and some of our members were understandably disappointed. They pay into the league all season, and it stings to see someone outside the league walk away with the pot. Guests can still play in our side games today, but we are reviewing whether to allow it next season.' },
      { type: 'p', text: 'Whatever you decide, make the guest policy clear in your bylaws before it becomes an issue.' },

      { type: 'h2', text: 'What Separates a Great League From One That Fizzles Out' },
      { type: 'p', text: 'After running our league, I believe the leagues that last get four things right:' },
      { type: 'ul', items: [
        'Good courses that players are excited to play',
        'Affordable entry fees and dues',
        'An even playing field, so everyone has a real chance to win',
        'A great group of people who genuinely enjoy being around one another',
      ] },
      { type: 'p', text: 'The last one matters most. You can fix a format, change a course, or adjust a payout. You cannot manufacture a group that likes spending a day on the course together. Recruit good people, help them get to know each other, and the rest of the league becomes much easier to run.' },

      { type: 'h2', text: 'Frequently Asked Questions' },
      { type: 'h3', text: 'How far in advance should I book tee times for a golf league?' },
      { type: 'p', text: 'We book courses and tee times six months or more in advance. For a group of 30 players, that lead time is the most reliable way to get the course and times you want.' },
      { type: 'h3', text: 'How do you split a golf league into flights?' },
      { type: 'p', text: 'We split flights strictly by handicap index. If your flights play different tees, explain to players that the split happens before course handicaps are calculated, so course handicaps can overlap between flights.' },
      { type: 'h3', text: 'Should league players be required to have a handicap index?' },
      { type: 'p', text: 'Yes. We require an active GHIN handicap index for every player and include the cost in annual dues. It keeps handicaps official and competition fair.' },
      { type: 'h3', text: 'What side games work well for a monthly golf league?' },
      { type: 'p', text: 'Our league pays out each month on Overall Net, Front 9 Net, Back 9 Net, Skins, Closest to the Pin, Long Drive, and Fewest Putts.' },
      { type: 'h3', text: 'How should a league handle no-shows?' },
      { type: 'p', text: 'Require prepayment at registration and set a clear cancellation deadline. In our league, players who cancel at least 24 hours in advance are covered, and no-shows forfeit their entry.' },
      { type: 'h3', text: 'Do players need to download an app to score?' },
      { type: 'pLink', text: 'Not with Scorify Golf. Players score from any phone\'s web browser by scanning a QR code or opening a link, with no app download or account required. You can', linkText: 'get started free', href: '/login', after: '.' },
    ],
  },
  {
    slug: 'golf-league-side-games-skins-ctp-payouts',
    title: 'Golf League Side Games: How to Run Skins, CTP, and Payouts',
    excerpt: 'How we split side game money across flights and the full field, run net skins with wraparound carryovers, and settle closest to the pin, long drive, and low putts without an argument.',
    date: '2026-09-28',
    category: 'Side Games',
    content: [
      { type: 'p', text: 'Side games are where a lot of the fun in a golf league happens. They give every player something to chase on every hole, not just the low handicappers fighting for first place.' },
      { type: 'p', text: 'I help run a monthly league with 40 players on the roster and two flights. Every event includes skins, closest to the pin, long drive, low putts, and net prizes for the full round and each nine. This post breaks down exactly how we structure the money, how we run each game, and the rules you need to settle before your first payout.' },

      { type: 'h2', text: 'How We Structure Side Game Money' },
      { type: 'p', text: "For our regular monthly events, side games are included in the entry fee. Nobody has to decide whether to buy in on the first tee, and nobody gets left out of a pot. Each player's side game money is split into two buckets: about 86% goes to flight pots and about 14% goes to full-field contests." },
      { type: 'h3', text: 'Flight Pots: About 86% of Side Game Money' },
      { type: 'p', text: "Most of the money stays within each flight, so players compete against others at a similar handicap level. Both flights use the same split. Here is how each flight's pot is divided:" },
      { type: 'ul', items: [
        '18-Hole Net: about 14% for 1st, 8% for 2nd, 6% for 3rd',
        'Front 9 Net: about 6% for 1st, 3% for 2nd',
        'Back 9 Net: about 6% for 1st, 3% for 2nd',
        'Skins: 50%',
        'Long Drive: about 6%',
      ] },
      { type: 'p', text: 'Percentages are rounded. Because every player contributes the same amount, each pot grows with the size of the flight, but the split stays the same whether a flight has 12 players or 18.' },
      { type: 'h3', text: 'Full-Field Pots: About 14% of Side Game Money' },
      { type: 'p', text: 'A few contests are open to everyone, regardless of flight:' },
      { type: 'ul', items: [
        'Low Putts: about 17%',
        'Closest to the Pin: about 21% on each of four par 3s',
      ] },
      { type: 'p', text: 'Together, the four closest-to-the-pin prizes make up about 83% of the full-field pot.' },
      { type: 'h3', text: 'Why We Split It This Way' },
      { type: 'p', text: 'We wanted an amount that felt fair and kept the whole group involved. Spreading the money across several games and several places keeps side games accessible to everyone, including the high handicappers. That is also why skins gets the biggest share.' },

      { type: 'h2', text: 'How to Run Net Skins' },
      { type: 'p', text: 'Skins is by far the most exciting game in our league. It is the one where even the highest handicappers in the group can go home with money, because a single great net score on one hole can win a skin.' },
      { type: 'h3', text: 'Net Skins by Flight' },
      { type: 'p', text: 'We play net skins within each flight. A player wins a skin by posting the lowest net score on a hole, outright. If two or more players tie for the low net score, nobody wins that hole and it carries over.' },
      { type: 'h3', text: 'Every Skin Is Worth the Same' },
      { type: 'p', text: "At the end of the round, we divide the flight's skins pot by the total number of skins won. Each skin is worth the same amount. If six skins are won, each one pays one-sixth of the flight's skins pot." },
      { type: 'h3', text: 'Wraparound Carryovers' },
      { type: 'p', text: 'Carryovers raise an obvious question: what happens when the last holes of the round tie? We use a wraparound rule. The carryover moves to hole 1, and whoever wins hole 1 outright also wins every skin carried over from the end of the round.' },
      { type: 'p', text: 'For example, if holes 16, 17, and 18 all tie, the player who wins hole 1 takes four skins: hole 1 plus the three carried over. With 12 or more players in a flight, a round where no hole produces a winner is nearly impossible. Even so, decide ahead of time what you would do if it happened.' },

      { type: 'h2', text: 'Running Closest to the Pin, Long Drive, and Low Putts' },
      { type: 'p', text: 'These contests are decided on the course, so they need a little setup before the round.' },
      { type: 'h3', text: 'Closest to the Pin and Long Drive' },
      { type: 'p', text: 'We place signs on each contest hole so players know when a closest-to-the-pin or long drive hole is coming up. We run closest to the pin on four par 3s for the full field, and long drive separately within each flight.' },
      { type: 'p', text: 'Scorify Golf automatically generates the printable signs and sheets you need for these contests, so there is no extra design or formatting work before each event.' },
      { type: 'h3', text: 'Low Putts' },
      { type: 'p', text: "Low putts is open to the full field and goes to the player with the fewest putts for the round. If players tie, we split the pot evenly among them. It is simple, easy to explain, and nobody feels shortchanged." },

      { type: 'h2', text: 'Paying Out Winners' },
      { type: 'p', text: 'We pay winners back through Venmo after the round. Because entry fees are prepaid, the money is already collected before anyone tees off, and payouts only flow one direction.' },
      { type: 'h3', text: 'From Excel to Next-Day Payouts' },
      { type: 'p', text: 'For years, we ran everything in Excel. With more than 20 separate prizes across two flights and the full field, plus wraparound skins to sort out, calculating who won what took time. It usually took three to four days to finalize results and send payouts.' },
      { type: 'p', text: 'Today, Scorify calculates every pot automatically as scores come in. We now finish payouts the next day instead of days later, and players get their winnings while the round is still fresh.' },

      { type: 'h2', text: 'Side Games for Special Events' },
      { type: 'p', text: 'Once a year, we host another club for a special event. That day calls for a few extra games on top of our usual lineup.' },
      { type: 'h3', text: 'Super Closest to the Pin' },
      { type: 'p', text: 'We add a Super CTP on the shortest par 3 on the course. It gives everyone a real shot at a bigger prize on a hole where a good swing matters more than handicap.' },
      { type: 'h3', text: 'Blind Partners' },
      { type: 'p', text: 'For blind partners, two players are paired at random and their net scores are added together. The pair with the lowest combined net score wins. Because partners are drawn at random, it can pair players from different clubs and gives everyone a chance to win alongside someone new.' },
      { type: 'h3', text: 'Handling Money Between Two Clubs' },
      { type: 'p', text: 'When two clubs play together, we mix the pots rather than running them club against club. The home club manages all outgoing payments. Having one club own the payouts keeps it simple and avoids confusion about who owes whom.' },

      { type: 'h2', text: 'Side Game Mistakes to Avoid' },
      { type: 'h3', text: 'Not Deciding How Ties Work Before the Round' },
      { type: 'p', text: 'The most common mistake I see is not accounting for ties, and not communicating how they will be handled. Everyone needs to be on the same page before results come in. If you make a tie decision after the scores are known, the optics can make it look like you are picking winners, even when the call is fair.' },
      { type: 'p', text: 'Write down how you handle each type of tie before the season starts:' },
      { type: 'ul', items: [
        'Skins: tied holes carry over, including the wraparound to hole 1.',
        'Low putts: tied players split the pot evenly.',
        'Net prizes: decide whether tied places split the combined prize money or use a tiebreaker.',
        'Every other contest: if there is any chance of a tie, settle the rule in advance.',
      ] },
      { type: 'h3', text: 'Letting Guests Into the Pots Without a Policy' },
      { type: 'p', text: 'We have allowed guests to play in our side games, and a few guests have taken home substantial winnings. Some members were understandably disappointed, since they pay into the league all season. We still allow it today, but we are reviewing whether to keep that policy next season. Whatever you choose, put it in your bylaws before it becomes an issue.' },

      { type: 'h2', text: 'A Simple Way to Start' },
      { type: 'p', text: 'If you are adding side games to your league for the first time, the simplest path is to use software that already supports them. Scorify Golf includes the formats we use every month, so you can choose your games when you set up the event and let payouts calculate automatically as scores come in.' },
      { type: 'p', text: 'If you are building your lineup from scratch, start with the games that are easiest to explain, then add more once your group is comfortable:' },
      { type: 'ul', items: [
        'Start with net skins and an 18-hole net prize. Skins gets the whole field excited, and an overall net prize rewards the best round of the day.',
        'Add closest to the pin on your par 3s, and long drive on a hole that suits it.',
        'Once the basics run smoothly, add front 9 and back 9 net prizes, low putts, and more paid places.',
        'Save extras like Super CTP and blind partners for special events.',
      ] },
      { type: 'p', text: 'Whatever you choose, keep the money spread across enough games and places that every handicap level has a real chance to win something.' },

      { type: 'h2', text: 'Frequently Asked Questions' },
      { type: 'h3', text: 'How do you calculate skins payouts?' },
      { type: 'p', text: 'Divide the skins pot by the total number of skins won. Each skin is worth the same amount. For example, if six skins are won, each skin pays one-sixth of the pot.' },
      { type: 'h3', text: 'What happens to skins carryovers at the end of the round?' },
      { type: 'p', text: 'In our league, carryovers wrap around to hole 1. If holes 16, 17, and 18 tie, the player who wins hole 1 outright takes all four skins.' },
      { type: 'h3', text: 'Should skins be gross or net in a golf league?' },
      { type: 'p', text: 'We play net skins within each flight. Net skins give higher handicappers a real chance to win, which is a big part of why skins is the most popular game in our league.' },
      { type: 'h3', text: 'How should a golf league divide side game money?' },
      { type: 'p', text: 'There is no single right split. Our league includes side games in the entry fee. About 86% of that money goes to flight pots, with half of each flight pot going to skins, and about 14% goes to full-field contests. Choose a split that feels fair for your group and keeps everyone involved.' },
      { type: 'h3', text: 'How do you handle ties in closest to the pin or low putts?' },
      { type: 'p', text: 'For low putts, we split the pot evenly among tied players. For every contest, the most important step is deciding the tie rule before the round and sharing it with players.' },
      { type: 'h3', text: 'Is there software that calculates golf side game payouts automatically?' },
      { type: 'pLink', text: 'Yes. Scorify Golf calculates skins, closest to the pin, long drive, low putts, and net prizes automatically as players enter scores on their phones, with no app download required. You can', linkText: 'get started free', href: '/login', after: '.' },
    ],
  },
  {
    slug: 'digital-vs-paper-golf-scoring',
    title: 'Digital vs. Paper Golf Scoring: What Changed When Our League Switched',
    excerpt: 'For years we scored on paper cards and entered everything by hand. Here is what paper scoring really cost us, what digital scoring looks like in practice, and how to decide if it is right for your league.',
    date: '2026-10-05',
    category: 'League Management',
    content: [
      { type: 'p', text: 'Every league commissioner eventually asks the same question: should we keep scoring on paper, or move to digital?' },
      { type: 'p', text: 'I help run a monthly golf league with a 40-player roster and 28 to 32 players at each event. For years, we scored on paper cards and entered everything by hand. This year we switched to digital scoring, and it changed tournament day for our players and our admin team. Here is what paper scoring really cost us, what digital scoring looks like in practice, and how to decide whether it is right for your league.' },

      { type: 'h2', text: 'How Paper Scoring Worked in Our League' },
      { type: 'p', text: "Our old process was simple on paper. Each foursome used the standard scorecards provided by the course, and two players in each group kept score. Before turning in their cards, the two scorekeepers reconciled them to make sure they matched." },
      { type: 'p', text: 'Once the cards came in, a league admin entered every score by hand into our scoring system. Reviewing and verifying everything took at least 90 minutes.' },
      { type: 'h3', text: 'The Scoring Table' },
      { type: 'p', text: 'Picture a table covered in 16 to 20 scorecards, with players waiting to find out who won. It was total chaos. One of us was stuck at a computer for close to two hours while everyone else waited.' },
      { type: 'h3', text: 'Where Paper Went Wrong' },
      { type: 'p', text: 'Even with two cards per group, mistakes got through:' },
      { type: 'ul', items: [
        'Illegible handwriting',
        'Addition errors',
        'Scores that did not match between the two cards',
      ] },
      { type: 'p', text: 'Those mistakes had real consequences. Results often had to be updated the next day. There were also times we had to correct payouts and send them again. Between data entry, corrections, and payouts, finalizing an event usually took three to four days.' },

      { type: 'h2', text: 'What Digital Scoring Looks Like Now' },
      { type: 'h3', text: 'No App Download, No Passwords' },
      { type: 'p', text: 'When we first tried a competing scoring app, two problems stopped us cold: every player had to download an app, and players could not remember their passwords. That is manageable a day or two before an event. It is not manageable the morning of, when a group is about to tee off.' },
      { type: 'p', text: 'That experience is why I was adamant that Scorify Golf would never require an app download. Our scoring runs in a web browser, and groups can open it three ways:' },
      { type: 'ul', items: [
        'Scanning a QR code',
        'Tapping an NFC tag',
        'Opening a link',
      ] },
      { type: 'image', src: '/images/blog/scorify-group-code-access-steps.webp', alt: 'Three Scorify Golf screens: open the scoring link, enter the five-character group code, and tap your name to start scoring' },
      { type: 'h3', text: 'One Designated Scorer Per Group' },
      { type: 'p', text: "Each group picks one designated scorer, who enters the group's scores after every hole. Every group has its own access code printed right on its scorecard, so there is no login and no account to create." },
      { type: 'image', src: '/images/blog/scorify-hole-score-entry.webp', alt: 'Scorify Golf hole-by-hole score entry screen showing four players with gross score, net score, and handicap strokes' },
      { type: 'h3', text: 'Custom Scorecards Still Matter' },
      { type: 'p', text: 'Going digital did not mean getting rid of printed scorecards. Each group now gets a custom scorecard with player names, handicaps, and course information, including which holes have closest to the pin and long drive. Players have everything they need in their hands before they tee off.' },
      { type: 'image', src: '/images/blog/scorify-custom-scorecard.webp', alt: 'Custom printed Scorify Golf scorecard with player names, flights, handicaps, QR code, group access code, and closest to the pin and long drive holes' },

      { type: 'h2', text: 'Keeping Digital Scores Accurate' },
      { type: 'p', text: "Digital scoring does not mean giving up on checks and balances. Our groups still keep a paper card alongside the digital scorecard. Before a group submits its scores, we require everyone in the group to get together and reconcile the paper card against the digital entries." },
      { type: 'p', text: 'That one step catches most mistakes before they ever reach the leaderboard, and it keeps players accountable for their own scores, just like paper always did.' },

      { type: 'h2', text: 'How Digital Scoring Changed League Day' },
      { type: 'h3', text: 'Winning Over the Old-School Players' },
      { type: 'p', text: 'A few of our old-school players pushed back at first. What won them over was seeing their results in real time. Being able to check where they stood during the round, and hear the winners announced within an hour of finishing, changed their minds quickly.' },
      { type: 'h3', text: 'A Live Leaderboard Makes the Round More Fun' },
      { type: 'p', text: 'The live leaderboard turned out to be one of the best parts of the switch. Players track their progress as they work through the round and see who is playing well and who is struggling. By the time everyone gets back to the 19th hole, they know exactly who they can give a hard time to.' },
      { type: 'image', src: '/images/blog/scorify-live-leaderboard.webp', alt: 'Scorify Golf live leaderboard showing Flight A net standings with course handicaps and gross scores' },
      { type: 'p', text: 'Our post-round gatherings have improved a lot. Everyone is engaged in how everyone else did, because the results are right there instead of days away.' },
      { type: 'h3', text: "Admins Get Their Day Back" },
      { type: 'p', text: "The biggest change for our admin team is what we do after the round: nothing more than enjoying everyone's company. Instead of one of us being chained to a computer for nearly two hours, we all get to mingle. We announce results the same day with minimal effort, and payouts that used to take three to four days are now finished the next day." },

      { type: 'h2', text: 'Planning for the Downsides' },
      { type: 'p', text: 'Digital scoring is not perfect, and it is worth planning for what can go wrong.' },
      { type: 'h3', text: 'Mismatched Scores' },
      { type: 'p', text: 'The main downside we see is mismatched scores, where the digital entry does not match the paper card. Honestly, that is not much different from the mismatches we used to get between two paper cards. The group reconciliation step before submitting is what catches them.' },
      { type: 'h3', text: 'Dead Phones' },
      { type: 'p', text: 'With four players in a group, at least one phone almost always has enough battery. As a backup, I bring my laptop to every event, so if manual entry is ever needed, we can handle it on the spot.' },
      { type: 'h3', text: 'Poor Cell Signal' },
      { type: 'p', text: 'Many courses have spotty coverage. Scorify is set up so that once a phone connects near the clubhouse, scores are saved locally on the device during the round and submitted as soon as a connection is available again.' },

      { type: 'h2', text: 'When Is Digital Scoring Worth It?' },
      { type: 'p', text: 'My rule of thumb: digital scoring becomes worth investing in once your normal group is bigger than two foursomes. Below that, paper is manageable. Above it, the data entry, the mistakes, and the wait for results start to add up quickly.' },
      { type: 'p', text: 'It is also worth remembering that scoring is only one piece of running a league. For us, digital scoring is a feature, not the whole point. Organizing groups and creating scorecards are just as important, and the right tool should handle those too.' },

      { type: 'h2', text: 'How to Make the Switch' },
      { type: 'p', text: 'Running a trial round before your first official event is always a good idea. It gives players a low-pressure chance to try it, and it gives you a chance to work out any questions. That said, the simpler the tool, the less onboarding you need. Simplicity was the main thing I designed Scorify around.' },
      { type: 'h3', text: 'What to Look for in a Digital Scoring Tool' },
      { type: 'p', text: 'When you compare options, two things matter most:' },
      { type: 'ul', items: [
        'Cost: league budgets are tight, so price should be a primary factor.',
        'User experience: if players struggle to use it on the first tee, nothing else matters. A poor user experience in the tools I tried is what led me to build Scorify.',
      ] },
      { type: 'p', text: 'Beyond those two, look for scoring that works in a web browser with no app download or account, and that keeps working when the cell signal drops.' },

      { type: 'h2', text: 'Frequently Asked Questions' },
      { type: 'h3', text: 'Is digital scoring better than paper for a golf league?' },
      { type: 'p', text: 'For most leagues with more than two foursomes, yes. In our league, digital scoring cut out roughly 90 minutes of manual data entry after each event, reduced scoring errors, and let us announce winners within an hour of finishing.' },
      { type: 'h3', text: 'Do players need to download an app for digital golf scoring?' },
      { type: 'p', text: 'Not with Scorify Golf. Players open the scorecard in a web browser by scanning a QR code, tapping an NFC tag, or opening a link. Each group uses an access code printed on its scorecard, so there is no app, account, or password.' },
      { type: 'h3', text: 'How do you keep digital golf scores accurate?' },
      { type: 'p', text: 'Keep a paper card as a backup, and require each group to reconcile its paper card with the digital scores before submitting.' },
      { type: 'h3', text: 'What happens if there is no cell signal on the course?' },
      { type: 'p', text: 'With Scorify, scores are saved on the phone during the round and submitted automatically once a connection is available again.' },
      { type: 'h3', text: 'Should every player in a group enter scores?' },
      { type: 'p', text: 'We use one designated scorer per group, who enters scores after each hole. It keeps entry simple and gives each group one clear owner for its scorecard.' },
      { type: 'h3', text: 'How can I try digital scoring for my league?' },
      { type: 'pLink', text: 'Run a trial round with your group first. You can', linkText: 'get started free', href: '/login', after: '.' },
    ],
  },
]

export function getBlogPost(slug) {
  return BLOG_POSTS.find(p => p.slug === slug)
}
